# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-17 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('address', models.CharField(max_length=100, verbose_name='联系地址')),
                ('messages', models.TextField(verbose_name='留言信息')),
            ],
            options={
                'verbose_name': '用户留言信息',
            },
        ),
    ]
